# Swagger definition for the TranscodeE16 Manifest
swagger: '2.0'

# Metadata
info:
  version: "0.0.1"
  title: ElasticsearchE16
  description: 'Earn bitcoin by hosting Elasticsearch as a service on the 21.co network.'
  termsOfService: https://opensource.org/licenses/MIT
  contact:
    email: james@esixteen.co
    name: eSixteen.co
    url: https://www.esixteen.co/apps/elastice16
  x-21-usage: 'Use the available API endpoints to index and search for your documents.'
  x-21-quick-buy: "21 buy url http://[fcce:a977:eec7:c71c:1c43:0000:0000:0001]:11016/status"
  x-21-category: utilities
  x-21-github-profile-url: https://github.com/pooleja
  x-21-keywords: [search, service, index, elastic, elasticsearch, iot, sensor]
  x-21-app-image: https://cdn.filepicker.io/api/file/xpq5tK5nSTm5ZuH2B3BW
  x-21-total-price:
     min: 10
     max: 10000
host: [fcce:a977:eec7:c71c:1c43:0000:0000:0001]:11016
schemes:
   - http
basePath: /
x-21-manifest-path: /manifest

# Available paths for the app
paths:
    /indexes:
    post:
      description: Creates a new index in ES.

      # Expected responses for this operation:
      responses:

        # Response code
        200:
          description: Successful response
          schema:
            title: Result
            type: object
            properties:
              success:
                type: boolean
              indexId:
                type: string
              indexExpireTime:
                type: number
              indexExpireDisplay:
                type: string
              expired:
                type: boolean
        # Response code
        500:
          description: Internal Error
          schema:
            title: Result
            type: object
            properties:
              success:
                type: boolean
              error:
                type: string

    /index_name:
    get:
      description: Gets the status of index_name

      # Expected responses for this operation:
      responses:

        # Response code
        200:
          description: Successful response
          schema:
            title: Result
            type: object
            properties:
              success:
                type: boolean
              indexId:
                type: string
              indexExpireTime:
                type: number
              indexExpireDisplay:
                type: string
              expired:
                type: boolean
        # Response code
        500:
          description: Internal Error
          schema:
            title: Result
            type: object
            properties:
              success:
                type: boolean
              error:
                type: string
        # Response code
        404:
          description: Failure or unable to find specified index
          schema:
            title: Result
            type: object
            properties:
              success:
                type: boolean
              error:
                type: string

    /index_name:
    delete:
      description: Deletes the index named index_name

      # Expected responses for this operation:
      responses:

        # Response code
        200:
          description: Successful response
          schema:
            title: Result
            type: object
            properties:
              success:
                type: boolean
              indexId:
                type: string
              message:
                type: string

        # Response code
        500:
          description: Internal Error
          schema:
            title: Result
            type: object
            properties:
              success:
                type: boolean
              error:
                type: string

    /index_name:
    put:
      description: Renews the index named index_name for 30 additional days

      # Expected responses for this operation:
      responses:

        # Response code
        200:
          description: Successful response
          schema:
            title: Result
            type: object
            properties:
              success:
                type: boolean
              indexId:
                type: string
              indexExpireTime:
                type: number
              indexExpireDisplay:
                type: string
              expired:
                type: boolean
        # Response code
        500:
          description: Internal Error
          schema:
            title: Result
            type: object
            properties:
              success:
                type: boolean
              error:
                type: string
        # Response code
        404:
          description: Failure or unable to find specified index
          schema:
            title: Result
            type: object
            properties:
              success:
                type: boolean
              error:
                type: string

    /index_name/document_type:
    post:
      description: Indexes the JSON document sent in the request to the specified index in ES.

      # Expected responses for this operation:
      responses:

        # Response code
        200:
          description: Successful response
          schema:
            title: Result
            type: object
            properties:
              success:
                type: boolean
              result:
                type: object

        # Response code
        500:
          description: Internal Error
          schema:
            title: Result
            type: object
            properties:
              success:
                type: boolean
              error:
                type: string
        # Response code
        404:
          description: Failure or unable to find specified index
          schema:
            title: Result
            type: object
            properties:
              success:
                type: boolean
              error:
                type: string

    /index_name/document_type/_search:
    post:
      description: Searches against the specified index and document type with the JSON query data passed into the request.

      # Expected responses for this operation:
      responses:

        # Response code
        200:
          description: Successful response
          schema:
            title: Result
            type: object
            properties:
              success:
                type: boolean
              result:
                type: object

        # Response code
        500:
          description: Internal Error
          schema:
            title: Result
            type: object
            properties:
              success:
                type: boolean
              error:
                type: string
        # Response code
        404:
          description: Failure or unable to find specified index
          schema:
            title: Result
            type: object
            properties:
              success:
                type: boolean
              error:
                type: string
